name: Test_ManualParams

parameters:
  - name: test-string-param
    displayName: 'test-string-param | Test string parameter'
    type: string
variables:
  - group: Atom

jobs:
  
  - job: TestManualParams
    pool:
      vmImage: ubuntu-latest
    steps:
      
      - checkout: self
        fetchDepth: 0
      
      - task: UseDotNet@2
        inputs:
          version: '9.0.x'

      - script: dotnet run --project _atom/_atom.csproj TestManualParams --skip --headless
        name: TestManualParams
        env:
          test-string-param: ${{ parameters.test-string-param }}
