name: Test_ValidatePrivateNugetFeed

variables:
  - group: Atom
trigger: none

jobs:
  
  - job: SetupBuildInfo
    pool:
      vmImage: ubuntu-latest
    steps:
      
      - checkout: self
        fetchDepth: 0
      
      - script: dotnet run --project _atom/_atom.csproj SetupBuildInfo --skip --headless
        name: SetupBuildInfo
  
  - job: PackPrivateTestLib
    pool:
      vmImage: ubuntu-latest
    steps:
      
      - checkout: self
        fetchDepth: 0
      
      - script: dotnet run --project _atom/_atom.csproj PackPrivateTestLib --skip --headless
        name: PackPrivateTestLib
      
      - task: PublishPipelineArtifact@1
        displayName: PrivateTestLib
        inputs:
          artifactName: PrivateTestLib
          targetPath: "$(Build.BinariesDirectory)/PrivateTestLib"
      
  
  - job: TestPrivateNugetRestore
    pool:
      vmImage: ubuntu-latest
    steps:
      
      - checkout: self
        fetchDepth: 0
      
      - script: dotnet tool update --global DecSm.Atom.Tool --prerelease
        displayName: 'Install atom tool'
      
      - script: |
          atom nuget-add --name "DecSm" --url "https://nuget.pkg.github.com/DecSmith42/index.json"
        displayName: 'Setup NuGet'
        env:
          NUGET_TOKEN_DECSM: $(PRIVATE_NUGET_API_KEY)
        
      - script: dotnet run --project _atom/_atom.csproj TestPrivateNugetRestore --skip --headless
        name: TestPrivateNugetRestore
