global using Atom.Targets;
global using Atom.Targets.Build;
global using Atom.Targets.Sandbox;
global using DecSm.Atom.Artifacts;
global using DecSm.Atom.Extensions.AzureKeyVault;
global using DecSm.Atom.Build.Definition;
global using DecSm.Atom.Extensions.AzureStorage;
global using DecSm.Atom.Extensions.Dotnet.Helpers;
global using DecSm.Atom.Extensions.GithubWorkflows;
global using DecSm.Atom.Extensions.GithubWorkflows.Generation.Options;
global using DecSm.Atom.Extensions.GitVersion;
global using DecSm.Atom.Hosting;
global using DecSm.Atom.Params;
global using DecSm.Atom.Workflows.Definition;
global using static Build;