global using Atom.Targets;
global using Atom.Targets.Build;
global using Atom.Targets.Test;
global using DecSm.Atom;
global using DecSm.Atom.Artifacts;
global using DecSm.Atom.Build;
global using DecSm.Atom.Module.AzureKeyVault;
global using DecSm.Atom.Build.Definition;
global using DecSm.Atom.Module.AzureStorage;
global using DecSm.Atom.Module.DevopsWorkflows;
global using DecSm.Atom.Module.DevopsWorkflows.Generation.Options;
global using DecSm.Atom.Module.Dotnet;
global using DecSm.Atom.Module.GithubWorkflows;
global using DecSm.Atom.Module.GithubWorkflows.Generation.Options;
global using DecSm.Atom.Module.GitVersion;
global using DecSm.Atom.Nuget;
global using DecSm.Atom.Params;
global using DecSm.Atom.Process;
global using DecSm.Atom.Workflows.Definition;
global using DecSm.Atom.Workflows.Definition.Command;
global using DecSm.Atom.Workflows.Definition.Options;
global using DecSm.Atom.Workflows.Definition.Triggers;
global using DecSm.Atom.Workflows.Options;
global using IPublishTester = Atom.Targets.Test.IPublishTester;
global using IPushToPrivateNuget = Atom.Targets.Test.IPushToPrivateNuget;
global using ITestAtom = Atom.Targets.Test.ITestAtom;
global using ITestPrivateNugetRestore = Atom.Targets.Test.ITestPrivateNugetRestore;
