namespace DecSm.Atom.SourceGenerators.Tests;

public class GenerateEntryPointSourceGeneratorTests
{
    [Test]
    public void EmptyDefinition_GeneratesDefaultSource()
    {
        // Arrange
        const string source = """
                              using DecSm.Atom.Build.Definition;

                              namespace TestNamespace;

                              [GenerateEntryPoint]
                              [BuildDefinition]
                              public partial class TestBuildDefinition : BuildDefinition;
                              """;

        var expectedGenerated = """
                                // <auto-generated/>

                                DecSm.Atom.Hosting.AtomHost.Run<TestNamespace.TestBuildDefinition>(args);
                                """.Replace("\r\n", "\n");

        // Act
        var generatedText = TestUtils.GetGeneratedSource<GenerateEntryPointSourceGenerator>(source, typeof(BuildDefinition).Assembly);

        // Assert
        TestContext.Out.Write(generatedText);
        generatedText.ShouldBe(expectedGenerated);
    }
}
