namespace Atom;

[BuildDefinition]
[GenerateEntryPoint]
internal sealed partial class Build : DefaultBuildDefinition
{
    private Target GenerateDotnetCliCode =>
        t => t.Executes(async () =>
        {
            var result = await ProcessRunner.RunAsync(new("dotnet", "--cli-schema"));
            var cliSchema = JsonDocument.Parse(result.Output);
            var rootCommand = DotnetCliParser.GetCommand("dotnet", cliSchema.RootElement);

            if (rootCommand is null)
                throw new("Failed to parse dotnet CLI schema");

            // Flatten subcommands to root level, names will be prefixed with parent command name/s (space separated)
            var flattenedCommands = new List<Command>();

            foreach (var subCommand in rootCommand.SubCommands)
                DotnetCliParser.FlattenCommands(string.Empty, subCommand, flattenedCommands);

            if (!FileSystem.Directory.Exists(FileSystem.AtomRootDirectory / "DecSm.Atom.Module.DotnetCli" / "Generated"))
                FileSystem.Directory.CreateDirectory(FileSystem.AtomRootDirectory / "DecSm.Atom.Module.DotnetCli" / "Generated");

            foreach (var command in flattenedCommands.Where(x => !x.Name.StartsWith('-')))
            {
                var writer = new CsharpWriter();

                writer.WriteLine("// <auto-generated/>");
                writer.WriteLine(string.Empty);
                writer.WriteLine("#nullable enable");
                writer.WriteLine(string.Empty);
                writer.WriteLine("using DecSm.Atom.Paths;");
                writer.WriteLine("using DecSm.Atom.Process;");
                writer.WriteLine("using JetBrains.Annotations;");
                writer.WriteLine(string.Empty);
                writer.WriteLine("namespace DecSm.Atom.Module.DotnetCli;");
                writer.WriteLine(string.Empty);

                DotnetCliGenerator.GenerateInterfaceCode(writer, command);
                DotnetCliGenerator.GenerateImplementationCode(writer, command);
                DotnetCliGenerator.GenerateOptionsCode(writer, command);

                await FileSystem.File.WriteAllTextAsync(FileSystem.AtomRootDirectory /
                                                        "DecSm.Atom.Module.DotnetCli" /
                                                        "Generated" /
                                                        $"{CsharpWriter.ToPascalCase(command.Name)}.cs",
                    writer.ToString());
            }
        });
}
