name: CleanupBuilds

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  
  CleanupPrereleaseArtifacts:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: CleanupPrereleaseArtifacts
        id: CleanupPrereleaseArtifacts
        run: dotnet run --project _atom/_atom.csproj CleanupPrereleaseArtifacts --skip --headless
