name: Cleanup

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  
  CleanupPrereleaseArtifacts:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: CleanupPrereleaseArtifacts
        id: CleanupPrereleaseArtifacts
        run: dotnet run --project _atom/_atom.csproj CleanupPrereleaseArtifacts --skip --headless
