name: Cleanup

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  
  Setup:
    runs-on: ubuntu-latest
    outputs:
      atom-build-id: ${{ steps.Setup.outputs.atom-build-id }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup
        id: Setup
        run: dotnet run --project _atom/_atom.csproj Setup --skip --headless
  
  CleanupPrereleaseArtifacts:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: CleanupPrereleaseArtifacts
        id: CleanupPrereleaseArtifacts
        run: dotnet run --project _atom/_atom.csproj CleanupPrereleaseArtifacts --skip --headless
