name: Sandbox

on:
  workflow_dispatch:

jobs:
  
  Setup:
    runs-on: ubuntu-latest
    outputs:
      atom-build-id: ${{ steps.Setup.outputs.atom-build-id }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup
        id: Setup
        run: dotnet run --project _atom/_atom.csproj Setup --skip --headless
  
  RunMatrix:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        matrix-val-1: [a, b, c]
        matrix-val-2: [1, 2, 3]
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: RunMatrix
        id: RunMatrix
        run: dotnet run --project _atom/_atom.csproj RunMatrix --skip --headless
        env:
          matrix-val-1: ${{ matrix.matrix-val-1 }}
          matrix-val-2: ${{ matrix.matrix-val-2 }}
