name: Test_BuildWithCustomArtifacts

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  
  Setup:
    runs-on: ubuntu-latest
    outputs:
      atom-build-id: ${{ steps.Setup.outputs.atom-build-id }}
      atom-build-version: ${{ steps.Setup.outputs.atom-build-version }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: Setup
        id: Setup
        run: dotnet run --project _atom/_atom.csproj Setup --skip --headless
        env:
          nuget-dry-run: true
  
  PackAtom:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: PackAtom
        id: PackAtom
        run: dotnet run --project _atom/_atom.csproj PackAtom --skip --headless
        env:
          nuget-dry-run: true
      
      - name: UploadArtifact
        run: dotnet run --project _atom/_atom.csproj UploadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom
  
  PackAtomTool:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: PackAtomTool
        id: PackAtomTool
        run: dotnet run --project _atom/_atom.csproj PackAtomTool --skip --headless
        env:
          nuget-dry-run: true
      
      - name: UploadArtifact
        run: dotnet run --project _atom/_atom.csproj UploadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom.Tool
  
  PackAzureKeyVaultModule:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: PackAzureKeyVaultModule
        id: PackAzureKeyVaultModule
        run: dotnet run --project _atom/_atom.csproj PackAzureKeyVaultModule --skip --headless
        env:
          nuget-dry-run: true
      
      - name: UploadArtifact
        run: dotnet run --project _atom/_atom.csproj UploadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom.Module.AzureKeyVault
  
  PackAzureStorageModule:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: PackAzureStorageModule
        id: PackAzureStorageModule
        run: dotnet run --project _atom/_atom.csproj PackAzureStorageModule --skip --headless
        env:
          nuget-dry-run: true
      
      - name: UploadArtifact
        run: dotnet run --project _atom/_atom.csproj UploadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom.Module.AzureStorage
  
  PackDevopsWorkflowsModule:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: PackDevopsWorkflowsModule
        id: PackDevopsWorkflowsModule
        run: dotnet run --project _atom/_atom.csproj PackDevopsWorkflowsModule --skip --headless
        env:
          nuget-dry-run: true
      
      - name: UploadArtifact
        run: dotnet run --project _atom/_atom.csproj UploadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom.Module.DevopsWorkflows
  
  PackDotnetModule:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: PackDotnetModule
        id: PackDotnetModule
        run: dotnet run --project _atom/_atom.csproj PackDotnetModule --skip --headless
        env:
          nuget-dry-run: true
      
      - name: UploadArtifact
        run: dotnet run --project _atom/_atom.csproj UploadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom.Module.Dotnet
  
  PackGithubWorkflowsModule:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: PackGithubWorkflowsModule
        id: PackGithubWorkflowsModule
        run: dotnet run --project _atom/_atom.csproj PackGithubWorkflowsModule --skip --headless
        env:
          nuget-dry-run: true
      
      - name: UploadArtifact
        run: dotnet run --project _atom/_atom.csproj UploadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom.Module.GithubWorkflows
  
  PackGitVersionModule:
    needs: [ Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: PackGitVersionModule
        id: PackGitVersionModule
        run: dotnet run --project _atom/_atom.csproj PackGitVersionModule --skip --headless
        env:
          nuget-dry-run: true
      
      - name: UploadArtifact
        run: dotnet run --project _atom/_atom.csproj UploadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom.Module.GitVersion
  
  TestAtom:
    needs: [ Setup ]
    strategy:
      matrix:
        job-runs-on: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.job-runs-on }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: TestAtom
        id: TestAtom
        run: dotnet run --project _atom/_atom.csproj TestAtom --skip --headless
        env:
          nuget-dry-run: true
          job-runs-on: ${{ matrix.job-runs-on }}
          matrix-slice: ${{ matrix.job-runs-on }}
      
      - name: UploadArtifact
        run: dotnet run --project _atom/_atom.csproj UploadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom.Tests
          matrix-slice: ${{ matrix.job-runs-on }}
  
  PushToNuget:
    needs: [ PackAtom, PackAtomTool, PackAzureKeyVaultModule, PackAzureStorageModule, PackDevopsWorkflowsModule, PackDotnetModule, PackGithubWorkflowsModule, PackGitVersionModule, Setup ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup NuGet
        run: |
          dotnet run --project DecSm.Atom.Tools.Nuget/DecSm.Atom.Tools.Nuget.csproj -- nuget-add --feed "DecSm;https://nuget.pkg.github.com/DecSm/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.NUGET_TOKEN_GH_FEED }}
        
      - name: DownloadArtifact
        run: dotnet run --project _atom/_atom.csproj DownloadArtifact --skip --headless
        env:
          atom-build-id: ${{ needs.Setup.outputs.atom-build-id }}
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
          atom-artifacts: DecSm.Atom,DecSm.Atom.Tool,DecSm.Atom.Module.AzureKeyVault,DecSm.Atom.Module.AzureStorage,DecSm.Atom.Module.DevopsWorkflows,DecSm.Atom.Module.Dotnet,DecSm.Atom.Module.GithubWorkflows,DecSm.Atom.Module.GitVersion
      
      - name: PushToNuget
        id: PushToNuget
        run: dotnet run --project _atom/_atom.csproj PushToNuget --skip --headless
        env:
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          nuget-dry-run: true
