name: Test_BuildPrivateNugetFeed

on:
  pull_request:
    branches:
      - 'main'

jobs:
  
  Setup:
    runs-on: ubuntu-latest
    outputs:
      atom-build-id: ${{ steps.Setup.outputs.atom-build-id }}
      atom-build-version: ${{ steps.Setup.outputs.atom-build-version }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup
        id: Setup
        run: dotnet run --project _atom/_atom.csproj Setup --skip --headless
        env:
          nuget-dry-run: true
  
  TestPrivateNugetRestore:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install atom tool
        run: dotnet tool install --global DecSm.Atom.Tools.Nuget --prerelease
        shell: bash
      
      - name: Setup NuGet
        run: |
            atom nuget-add --name "DecSm" --url "https://nuget.pkg.github.com/DecSmith42/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.PRIVATE_NUGET_API_KEY }}
        
      - name: TestPrivateNugetRestore
        id: TestPrivateNugetRestore
        run: dotnet run --project _atom/_atom.csproj TestPrivateNugetRestore --skip --headless
        env:
          nuget-dry-run: true
  
  PackPrivateTestLib:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: PackPrivateTestLib
        id: PackPrivateTestLib
        run: dotnet run --project _atom/_atom.csproj PackPrivateTestLib --skip --headless
        env:
          nuget-dry-run: true
      
      - name: Upload PrivateTestLib
        uses: actions/upload-artifact@v4
        with:
          name: PrivateTestLib
          path: "${{ github.workspace }}/.github/publish/PrivateTestLib"
      
  
  PushToPrivateNuget:
    needs: [ PackPrivateTestLib ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Download PrivateTestLib
        uses: actions/download-artifact@v4
        with:
          name: PrivateTestLib
          path: "${{ github.workspace }}/.github/artifacts/PrivateTestLib"
      
      - name: PushToPrivateNuget
        id: PushToPrivateNuget
        run: dotnet run --project _atom/_atom.csproj PushToPrivateNuget --skip --headless
        env:
          azure-vault-address: ${{ secrets.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ secrets.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ secrets.AZURE_VAULT_APP_ID }}
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          private-nuget-api-key: ${{ secrets.PRIVATE_NUGET_API_KEY }}
          nuget-dry-run: true
