name: Test_ValidatePrivateNugetFeed

on:
  pull_request:
    branches:
      - 'main'

jobs:
  
  SetupBuildInfo:
    runs-on: ubuntu-latest
    outputs:
      build-id: ${{ steps.SetupBuildInfo.outputs.build-id }}
      build-version: ${{ steps.SetupBuildInfo.outputs.build-version }}
      build-timestamp: ${{ steps.SetupBuildInfo.outputs.build-timestamp }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: SetupBuildInfo
        id: SetupBuildInfo
        run: dotnet run --project _atom/_atom.csproj SetupBuildInfo --skip --headless
  
  PackPrivateTestLib:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: PackPrivateTestLib
        id: PackPrivateTestLib
        run: dotnet run --project _atom/_atom.csproj PackPrivateTestLib --skip --headless
      
      - name: Upload PrivateTestLib
        uses: actions/upload-artifact@v4
        with:
          name: PrivateTestLib
          path: "${{ github.workspace }}/.github/publish/PrivateTestLib"
      
  
  TestPrivateNugetRestore:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install atom tool
        run: dotnet tool install --global DecSm.Atom.Tool --prerelease
        shell: bash
      
      - name: Setup NuGet
        run: |
            atom nuget-add --name "DecSm" --url "https://nuget.pkg.github.com/DecSmith42/index.json"
        shell: bash
        env:
          NUGET_TOKEN_DECSM: ${{ secrets.PRIVATE_NUGET_API_KEY }}
        
      - name: TestPrivateNugetRestore
        id: TestPrivateNugetRestore
        run: dotnet run --project _atom/_atom.csproj TestPrivateNugetRestore --skip --headless
