name: Test_ReleaseArtifact_Upload

on:
  workflow_dispatch:

jobs:
  
  PackAtom:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: PackAtom
        id: PackAtom
        run: dotnet run --project _atom/_atom.csproj PackAtom --skip --headless
      
      - name: Upload DecSm.Atom
        uses: actions/upload-artifact@v4
        with:
          name: DecSm.Atom
          path: "${{ github.workspace }}/.github/publish/DecSm.Atom"
  
  TestGithubReleaseAssetUpload:
    needs: [ PackAtom ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Download DecSm.Atom
        uses: actions/download-artifact@v4
        with:
          name: DecSm.Atom
          path: "${{ github.workspace }}/.github/artifacts/DecSm.Atom"
      
      - name: TestGithubReleaseAssetUpload
        id: TestGithubReleaseAssetUpload
        run: dotnet run --project _atom/_atom.csproj TestGithubReleaseAssetUpload --skip --headless
        env:
          azure-vault-app-secret: ${{ secrets.AZURE_VAULT_APP_SECRET }}
          azure-vault-address: ${{ vars.AZURE_VAULT_ADDRESS }}
          azure-vault-tenant-id: ${{ vars.AZURE_VAULT_TENANT_ID }}
          azure-vault-app-id: ${{ vars.AZURE_VAULT_APP_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
